<?php


/**
 * 
 * Implements hook_menu_local_tasks
 *
 */



function config_menu_dropdown_menu_local_tasks(&$variables) {
  if (!path_is_admin(current_path())) {
    $output = '';

    if (!empty($variables['primary'])) {
      $variables['primary']['#prefix'] = '<div class="config-dropdown">';
      $variables['primary']['#prefix'] .= '<span class="config-dropdown__button js-config-dropdown__button"><i class="fa fa-cogs" aria-hidden="true"></i> </span>';
      $variables['primary']['#prefix'] .= '<h2 class="element-invisible">' . t('Configuration Menu') . '</h2>';
      $variables['primary']['#prefix'] .= '<ul class="config-dropdown__menu">';
      $variables['primary']['#suffix'] = '</ul>';
      $variables['primary']['#suffix'] .= '</div><!--end config dropdown menu-->';
      $output .= drupal_render($variables['primary']);
    }

    return $output;
  }
}

function config_menu_dropdown_menu_local_task($variables) {
  if (!path_is_admin(current_path())) {   $link = $variables['element']['#link'];
  $link_text = $link['title'];

  if (!empty($variables['element']['#active'])) {
    // Add text to indicate active tab for non-visual users.
    $active = '<span class="element-invisible">' . t('(active tab)') . '</span>';

    // If the link does not contain HTML already, check_plain() it now.
    // After we set 'html'=TRUE the link will not be sanitized by l().
    if (empty($link['localized_options']['html'])) {
      $link['title'] = check_plain($link['title']);
    }
    $link['localized_options']['html'] = TRUE;
    $link_text = t('!local-task-title!active', array('!local-task-title' => $link['title'], '!active' => $active));
  }

  return '<li class="config-dropdown__menu__item' . (!empty($variables['element']['#active']) ? ' active' : '') . '">' . l($link_text, $link['href'], $link['localized_options']) . "</li>\n";


  }
}
